package com.code.SpringCachingProject.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.*;

//  used lombok to create constructor,getter & setter,toString method

@Entity
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
public class Weather {

    // Weather entity class with its fields

    @Id             // made it primary key
    @GeneratedValue(strategy = GenerationType.AUTO)     //Id will be autogenerated
    private Long id;

    private String city;

    private String forecast;

}
